### ISSUE TITLE
Issue 6 for Milestone 3: Training the model

### ISSUE THREAD

**Issue by josephwatunu123** [josephwatunu123/BI-personal-Project#6]
- [x] Data splitting
- [x] Bootstrapping
- [x] Cross validation (basic, repeated or LOOCV)
- [ ] Model training for either classification, regression, association, or clustering (as applicable)
- [ ] Model performance comparison using resamples (for classification and regression)
